baseurl: 
title: Filmprojektor
subtitle: Filmreviews
author: Konrad Bucher
description: Ein Blog über Filme
url: http://filmprojektor.net
keywords: Movies, Filme, Film, Rezension, Filmkritik, Filmkritiken, Filmrezensionen, Rezensionen, Movie
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
destination: docs/
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md

staticmanUrl: https://gautschbrett.herokuapp.com/v2/entry/knautschzone/filmprojektor/main/comments

collections:
  - comments

collections:
  comments:
    sort_by: date
